### PR TITLE
TimeConverter + csproj

### PR DESCRIPTION
**Pull request by anovik**
Added TimeConverter class + unit tests for it.

Migrated xproj to csproj since xproj is outdated now.

### CODE REVIEW

**Comment by Nick-Lucas** [comment]
Thanks so much for this!

~Could you add a tests file like [this](https://github.com/Stratajet/UnitConversion/blob/master/UnitConversionTests/MassConverterTests.cs)?~ scrap that, I missed the file in my scan over!

~Otherwise~ I'll be really happy to merge this once I've fixed the build process under csproj, but that one's on me!

**Comment by anovik** [comment]
Yes, tests are in TimeConverterTests.cs. 

Build process is currently broken, I hope it would be easy to repair it, just build directly from csproj.

**Comment by Nick-Lucas** [comment]
Hi Anna,

I've updated the build process and pulled in your classes. I also thought it would be a good idea to include fractions of seconds and a leap-year unit in the class so have added those.

I've opened PR #7 if you'd like to give it a look over? 

Hope it's okay that I've broken the code away from your PR, it was just easier than wrangling (it needed a re-base, and migration commit to be removed) with git, this time!

**Comment by anovik** [comment]
Hi Nick-Lucas,

I think your changes are ok. Sorry for this mess, I should supply the changes in two different pull requests and from different branches.

**Comment by Nick-Lucas** [comment]
Not a problem at all, for something this small it's hardly worth the extra effort, and it's a good prompt for me to finally update this solution!
I'll push out a new version with your changes shortly :)

**Pull request closed without merging**
