### PR TITLE
Added higher mass units in MassConverter

### PR DESCRIPTION
**Pull request by prasadtelkikar**
Added KgToQuintal, KgToShortTon, KgToLongTon converter in MassConverter.cs file.
Added unit tests for the same.

Reference:
[CCST-Conversion-Docuement](https://www.isa.org/uploadedFiles/Content/Training_and_Certifications/ISA_Certification/CCST-Conversions-document.pdf)
[Google - kg to quintal](https://www.google.co.in/search?ei=zAkHW8HbCcXbvAS70qOYBw&q=kg+to+quintal&oq=kg+to+q&gs_l=psy-ab.3.0.35i39k1j0l8.3665.3665.0.5477.1.1.0.0.0.0.118.118.0j1.1.0....0...1.1.64.psy-ab..0.1.117....0.ErLmVf0diBU)

### CODE REVIEW

**Comment by prasadtelkikar** [comment]
@gkampolis, is this PR acceptable? Is there any changes I need to do for this PR?

**Comment by gkampolis** [comment]
Sorry, busy week. Gonna see the build results but everything seems ok, so merged :)

Thanks for contributing!

**Comment by gkampolis** [comment]
Build succeeded, I've incremented the version no. and it should show up to nuget any minute now. :+1:

**Comment by prasadtelkikar** [comment]
@gkampolis  Hi,
Thanks for accepting my first PR for this project.
I pushed temperature converter with unit tests, which I found not at par with your coding standard.
Could you please review it and let me know, how can we improve this code?
or How we should implement temperature converter in cleaner way?
I would like to work on your suggestions.
Speed converter is also in my bucket list. Could like to give some suggestions for the same.

Code changes for temperature conversion: [7c6bcb5](https://github.com/prasadtelkikar/UnitConversion/commit/a082734722a52e5adc8bfe912e1da9c80970e549)

**Comment by gkampolis** [comment]
Most of the stuff you can see in the codebase are essentially inherited from previous development.

I did not have the time to tackle the  indeed necessary refactoring, however I'm more than happy to:
- accept proposed refactoring.
- add you as a collaborator in the project (and I'll be more helpful when I eventually have some more free time!) This option would give you a bit more autonomy and we can move things along a bit more speedily.

If you're interested in the second option, let me know and we can proceed from there. :)

**Comment by prasadtelkikar** [comment]
**Yes, I am interested** to be a collaborator for this project.
This will give me more exposure to open source project and it will be a great opportunity to learn.
As I am new to open source and contributing to easy task till now.  Need your guidance for the same.

**Comment by gkampolis** [comment]
Don't fret, this is my first project that I'm maintaining, so I'm learning as well!

I'll add you as a collaborator later tonight, once I get home.

**Comment by gkampolis** [comment]
@prasadtelkikar I've added you as a collaborator!

**Comment by prasadtelkikar** [comment]
@gkampolis I accepted your request. Now I got collaborator access to this repository.
Regarding changes for Temperature converter which I did here: [7c6bcb5](https://github.com/prasadtelkikar/UnitConversion/commit/a082734722a52e5adc8bfe912e1da9c80970e549), I expect some one should review this changes and suggest if there is any changes I need to do or should approve my changes. 
If this changes looks good then I can raise PR for the same.
Because I personally believe, that this code is strongly coupled and we can not use it for other converters. How could we generalize this code? Any suggestions/ recommendations are most welcome

**Comment by gkampolis** [comment]
@akritikos  wanna have a look?

**Comment by gkampolis** [comment]
@prasadtelkikar can you please hold on further commits as @akritikos is preparing a restructuring of the project, with probably breaking changes?

**Comment by prasadtelkikar** [comment]
@gkampolis, @akritikos 
Ok will not commit any bug fixes or enhancement till I get next instructions.

Thanks,
Prasad

**Pull request merged**
