### PR TITLE
Fixed kelvin to celsius conversion ratio

### PR DESCRIPTION
**Pull request by akshaybheda**
# Fixes #(23)Temperature: Celsius to Kelvin issue

## Changes proposed
Refactored the Kelvin to Celsius conversion

### CODE REVIEW

**Review by akshaybheda — COMMENTED** [review]
@prasadtelkikar Please review

**Review by prasadtelkikar — COMMENTED** [review]
Looks good to me

**Comment by atulmish** [comment]
Hi @prasadtelkikar 

I've noticed that the "Merge pull request #24"  has failed due to the incorrect Nuget key.

Are you happy with the changes to be published to Nuget? If so then I will sort out the key and publish it to the Nuget over this weekend.

If you have any concerns just shout!

Thanks
A

**Comment by prasadtelkikar** [comment]
@atulmish , Please add this changes to next nuget version.

**Pull request merged**
